- name: Playbook - VM 1
  hosts: server-VM1
  tasks:
  - name: Check Updates
    apt:
      update_cache: true

  - name: Instalação do Java
    apt:
      name: openjdk-11-jdk
      state: present
  
  - name: Adicionando a chave do repositório de instalação Jenkins
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: Adicionando repositório de instalação Jenkins
    apt_repository: 
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present

  - name: Instalação do Jenkins
    apt:
      name: jenkins
      state: present
      update_cache: true

  - name: Obtendo chave initialAdminPassword do Jenkins
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: chave

  - name: Exibindo chave initialAdminPassword do Jenkins
    debug: 
      msg: '{{ chave.stdout }}'