global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zabbix-agent'
    static_configs:
      - targets: ['172.22.0.5:10050']

  - job_name: 'mysql'
    static_configs:
      - targets: ['172.22.0.2:3306']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.22.0.8:9100']