[ Sonarqube ]
 - Create Project - Manually
 - Salve token

[ Jenkins ]
 - Painel de Controle > Gerenciar Jenkins > Gerenciar Extensões > Extensões disponíveis
   - Instalar plugin 'SonarQube Scanner'
 - Painel de Controle > Gerenciar Jenkins > Manage Credentials
   - Clique em 'System'
   - Clique em 'Global credentials (unrestricted)'
   - Clique em 'Add Credentials'
   - Kind 'Select text' > Scope 'Global' > Secret 'token-sonarqube' > ID 'nome-da-credentials'
 - Painel de Controle > Gerenciar Jenkins > Configurar o sistema
   - Procure a sessão 'SonarQube servers'
   - Ative 'Environment variables'
   - Clique em 'Add SonarQube'
   - Nome 'sonarqube-name' ..esse nome será usado depois para interagir com o Jenkinsfile
   - Em Server URL 'http://192.168.0.20:9000/' ..ou qualquer outr URL referente ao SonarQube
   - Em 'Server authentication token' selecione o token criado anteriormente
   - Clique em Salvar
 - Painel de Controle > Gerenciar Jenkins > Ferramenta de configuração global
   - Procure a sessão 'SonarQube Scanner'
   - Clique em 'Adicionar SonarQube Scanner'
   - Preencha o 'Name' ..pode colocar o mesmo nome da versão do SonarQube Scanner: 'SonarQubeScanner-4.6.2'
   - Clique em 'Apply' depois em 'Save'
 - Agora você pode criar uma nova tarefa 'Pipeline'
